{% set name = "smopy" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smopy-{{ version }}.zip
  sha256: fe71c6fe64490ab76a61124c2feefd85d841285f3943db7e3af0cff0b9c8a05f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - ipython
    - matplotlib-base
    - numpy
    - pillow
    - python >=3.0
    - six

test:
  imports:
    - smopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://packages.python.org/smopy
  summary: OpenStreetMap image tiles in Python
  license: BSD-1-Clause
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - julian-belina
