{% set name = "smopy" %}
{% set version = "0.0.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smopy-{{ version }}.tar.gz
  sha256: 7f9313b8bf98cd886d07d7094584a48bf0aca409d78b67e9d348e47b335b799f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools 
  run:
    - matplotlib-base
    - numpy
    - pillow
    - python >={{ python_min }}
    - six

test:
  imports:
    - smopy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rossant/smopy
  summary: OpenStreetMap image tiles in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
